# Generated by Django 5.1.6 on 2025-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPSQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.IntegerField()),
                ('lang_id', models.TextField()),
                ('question_number', models.IntegerField()),
                ('regexp_replace', models.TextField()),
                ('question_name', models.TextField()),
                ('question_type', models.TextField()),
            ],
        ),
    ]
