# Generated by Django 5.1.6 on 2025-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyResponseCounts',
            fields=[
                ('year_month', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'monthly_response_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTypeSummary',
            fields=[
                ('question_type', models.TextField(primary_key=True, serialize=False)),
                ('response_count', models.IntegerField()),
            ],
            options={
                'db_table': 'question_type_summary',
                'managed': False,
            },
        ),
    ]
