# Generated by Django 5.1.6 on 2025-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSSurveytypes',
            fields=[
                ('survey_type', models.IntegerField(primary_key=True, serialize=False)),
                ('survey_name', models.TextField()),
            ],
        ),
    ]
