# Generated by Django 5.1.6 on 2025-03-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_npsresponses_npssurvey_npssurveytypes_npsquestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NpsSurvey',
        ),
    ]
