# Generated by Django 5.1.6 on 2025-02-24 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_npssurveytypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsquestions',
            name='survey_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.npssurveytypes'),
        ),
    ]
