# Generated by Django 5.1.6 on 2025-02-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_npsquestions_survey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npsquestions',
            name='survey_type',
            field=models.ForeignKey(db_column='survey_type', on_delete=django.db.models.deletion.CASCADE, to='calc.npssurveytypes'),
        ),
    ]
