# Generated by Django 5.1.6 on 2025-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_npssurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npssurvey',
            name='msisdn',
            field=models.CharField(max_length=50),
        ),
    ]
