# Generated by Django 5.1.6 on 2025-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_npsquestions_survey_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_dttm', models.TextField()),
                ('msisdn', models.TextField()),
                ('response_dttm', models.TextField()),
                ('question_number', models.IntegerField()),
                ('question_name', models.TextField()),
                ('question_type', models.TextField()),
                ('response_raw', models.TextField()),
                ('response_parsed', models.TextField()),
            ],
        ),
    ]
