# Generated by Django 5.1.6 on 2025-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_npssurvey_account_type_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npssurvey',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
