# Generated by Django 5.1.6 on 2025-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_npssurvey_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npssurvey',
            name='visit_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
