# Generated by Django 5.1.6 on 2025-03-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_alter_npssurvey_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npssurvey',
            name='file_uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
