# Generated by Django 5.1.6 on 2025-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_alter_npssurvey_file_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSOverview',
            fields=[
                ('label', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('percentage', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'nps_overview',
                'managed': False,
            },
        ),
    ]
