# Generated by Django 5.1.6 on 2025-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_npsresponsesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySurveySummary',
            fields=[
                ('month_year', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('active', models.BigIntegerField()),
                ('completed', models.BigIntegerField()),
                ('stopped', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Monthly Survey Summary',
                'verbose_name_plural': 'Monthly Survey Summaries',
                'db_table': 'monthly_survey_summary',
                'managed': False,
            },
        ),
    ]
