# Generated by Django 5.1.6 on 2025-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_monthlysurveysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgNpsPerRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_region_name', models.CharField(max_length=100)),
                ('avg_nps_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'avg_nps_per_region_test',
                'ordering': ['-avg_nps_score'],
                'managed': False,
            },
        ),
    ]
