# Generated by Django 5.1.6 on 2025-04-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_avgnpsperregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyResponseCounts',
            fields=[
                ('response_date', models.DateField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_response_counts',
                'managed': False,
            },
        ),
    ]
