# Generated by Django 5.1.6 on 2025-04-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_dailyresponsecounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('type', models.TextField()),
                ('code', models.IntegerField()),
                ('regexp_replace', models.TextField()),
                ('survey_dttm', models.TextField()),
                ('msisdn', models.TextField()),
            ],
        ),
    ]
