# Generated by Django 5.1.6 on 2025-04-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_reportreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportreason',
            name='regexp_replace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
